{% set name = "mlens" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlens-{{ version }}.tar.gz
  sha256: 8f5a10ae0b5ef8ff83c95e617fa294e012d9b96704c29cc977dc75fb44f4b593

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - numpy >=1.11
  run:
    - python >=3.6
    - numpy >=1.11
    - scipy >=0.17

test:
  imports:
    - mlens
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flennerhag/mlens
  summary: Machine Learning Ensemble Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
